CREATE DATABASE IF NOT EXISTS palmyra_demo;

CREATE TABLE IF NOT EXISTS `supplier` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	`email` VARCHAR(64) NULL DEFAULT NULL,
	`phone_number` VARCHAR(64) NULL DEFAULT NULL,
	`address` VARCHAR(255) NULL DEFAULT NULL,
	`created_by` VARCHAR(128) NOT NULL,
	`created_on` DATETIME NOT NULL,
	`last_upd_by` VARCHAR(128) NULL DEFAULT NULL,
	`last_upd_on` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `uq_supplier_name` (`name`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;
